### PR TITLE
Move OS Specific code to separate files, remove duplication.

### LINKED ISSUE #5: Re-enable macOS support
Thanks for the great project. I used the tagged version but wanted to contribute so switched to master, where I had some trouble:

On master the project no longer works on `darwin`, but it does in 0.1.1.
The change for a windows fix moved `audio.go` (and video.go) to a `-windows` and `-linux` suffix, but there is no `-darwin` so compile fails.

### PR DESCRIPTION
**Pull request by andydotxyz**
Also fix up macOS long vs longlong issue.
Fixes #5

### CODE REVIEW

**Comment by zergon321** [comment]
I've added some changes. Please test the branch on **Mac OS** (without deleting `import "C"` from `platfrom_darwin.go`). Also there were missing imports at first so I would like to know how you built the player example and what editor or IDE you used for contributing.

**Comment by andydotxyz** [comment]
The IDE is GoLand. I had some problems with line endings that might have contributed to the missing line on Darwin file.

My testing on Linux was wrong - good catch. Retested now and it’s fine, thanks for the update.

**Comment by andydotxyz** [comment]
That’s Darwin and Linux happy at this end, if you tested Windows I think it’s good to go :) apologies again for the slip-up

**Comment by zergon321** [comment]
Good. Thank you.

**Comment by andydotxyz** [comment]
> Good. Thank you.

Thank you for this and for the excellent library.

**Pull request merged**
